/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Enfermero;
import modelo.Paciente;
import modelo.Paciente_vacuna;
import modelo.Vacuna;
import org.w3c.dom.events.Event;


public class EnfermeroForm extends javax.swing.JFrame {

    private LoginForm inicio;
    private String enfermero;
    private Icon icono_exito;
    
    public EnfermeroForm(LoginForm i, String enf) {
        this.inicio = i;
        this.enfermero = enf;
        initComponents();
        this.cambias_iconos();
        this.setLocationRelativeTo(null);       
        this.lblEnf.setText(enf);
        icono_exito = new ImageIcon("imagenes/icono_success.png");
        this.listarVacunas();
    }

    private void cambias_iconos() {
        ImageIcon icono = new ImageIcon("imagenes/Logo.png");
        this.imgLogin.setIcon(icono);
    }
    
    private void listarVacunas(){
        this.cmbVacuna.removeAllItems();
        this.cmbVacuna.addItem("Seleccionar...");
        ArrayList<Vacuna> listado = this.inicio.getControlador().listarVacunas();
        for(int i=0; i<listado.size(); i++){
            this.cmbVacuna.addItem(listado.get(i).getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNomPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedPaciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDirPaciente = new javax.swing.JTextField();
        txtEdadPaciente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnBuscarPaciente = new javax.swing.JButton();
        btnRegistroPaciente = new javax.swing.JButton();
        btnModificarPaciente = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCedVacuna = new javax.swing.JTextField();
        btnRegistroVacuna = new javax.swing.JButton();
        btnBuscarVacuna = new javax.swing.JButton();
        cmbVacuna = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        lblDosisVacuna = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObsVacuna = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarAdmin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblEnf = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        imgLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MIS VACUNAS APP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("1090415914 - CARLOS D. MARQUEZ V.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGENIERÍA DE SISTEMAS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROGRAMACIÓN ORIENTADA A OBJETOS");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtNomPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cédula");

        txtCedPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Teléfono");

        txtTelPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Dirección");

        txtDirPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEdadPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Edad");

        btnBuscarPaciente.setText("BUSCAR");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnRegistroPaciente.setText("REGISTRAR");
        btnRegistroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacienteActionPerformed(evt);
            }
        });

        btnModificarPaciente.setText("MODIFICAR");
        btnModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPacienteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Observaciones");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtNomPaciente)
                            .addComponent(txtTelPaciente)
                            .addComponent(txtDirPaciente)
                            .addComponent(txtEdadPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistroPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("GESTIÓN PACIENTES", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Cédula");

        txtCedVacuna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnRegistroVacuna.setText("REGISTRAR");
        btnRegistroVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroVacunaActionPerformed(evt);
            }
        });

        btnBuscarVacuna.setText("BUSCAR");
        btnBuscarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVacunaActionPerformed(evt);
            }
        });

        cmbVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        cmbVacuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVacunaItemStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Observaciones");

        lblDosisVacuna.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblDosisVacuna.setText("Cantidad de vacunas en inventario");

        txtObsVacuna.setColumns(20);
        txtObsVacuna.setRows(5);
        jScrollPane2.setViewportView(txtObsVacuna);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Vacunas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDosisVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(cmbVacuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedVacuna))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistroVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCedVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistroVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDosisVacuna)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("GESTIÓN DE VACUNAS", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENFERMERO");

        btnCerrarAdmin.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrarAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCerrarAdmin.setText("CERRAR SESIÓN");
        btnCerrarAdmin.setToolTipText("");
        btnCerrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarAdminActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        lblEnf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnf.setText("jLabel7");

        jLabel8.setText("Todos los derechos reservados.");

        jLabel9.setText("© 2021.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEnf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnCerrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(64, 64, 64))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEnf))
                .addGap(18, 18, 18)
                .addComponent(btnCerrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(imgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("GESTIÓN PACIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarAdminActionPerformed
        this.dispose();
        this.inicio.setVisible(true);
        this.inicio.getTxtUsuarioLogin().setText("");
        this.inicio.getTxtClaveLogin().setText("");
        this.inicio.getCmbTipoLogin().setSelectedIndex(0);
    }//GEN-LAST:event_btnCerrarAdminActionPerformed

    private void btnRegistroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacienteActionPerformed
        String cedula = this.txtCedPaciente.getText();
        String nombre = this.txtNomPaciente.getText();
        String telefono = this.txtTelPaciente.getText();
        String direccion = this.txtDirPaciente.getText();
        String edad = this.txtEdadPaciente.getText();
        String observacion = this.txtObs.getText();

        if (cedula.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || direccion.isEmpty() || edad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos...", "FALTA INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Paciente pac = new Paciente(cedula, nombre, telefono, direccion, Integer.parseInt(edad));
            boolean registro = this.inicio.getControlador().registrarPaciente(pac);
            if (registro) {
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "Se ha registrado el paciente exitosamente", "PACIENTE REGISTRADO", JOptionPane.PLAIN_MESSAGE, this.icono_exito);
            } else {
                JOptionPane.showMessageDialog(this, "El paciente ya se encuentra registrado...", "PACIENTE NO REGISTRADO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistroPacienteActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        String cedula = this.txtCedPaciente.getText();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la cédula para buscar al paciente...", "FALTA INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Paciente pac = this.inicio.getControlador().buscarPaciente(cedula);
            if (pac != null) {
                this.txtNomPaciente.setText(pac.getNombre());
                this.txtTelPaciente.setText(pac.getTelefono());
                this.txtDirPaciente.setText(pac.getDireccion());
                this.txtEdadPaciente.setText(""+pac.getEdad());
                ArrayList<Paciente_vacuna> pv = this.inicio.getControlador().buscarPacienteVacuna(cedula);
                if(pv.size() > 0){
                    String cad = "El paciente "+this.inicio.getControlador().buscarPaciente(pv.get(0).getPaciente()).getNombre()+"\ntiene puestas las siguientes dosis:";
                    for (int i = 0; i < pv.size(); i++) {
                        cad += "\n\nVacuna= " + this.inicio.getControlador().buscarVacunaID(pv.get(i).getVacuna()).getNombre() + 
                                "\nPuesta por= " + this.inicio.getControlador().buscarEnfermero(pv.get(i).getEnfermero()).getNombre()+ 
                                "\nFecha= " + pv.get(i).getFecha();
                        this.txtObs.setText(cad);
                    }
                }else{
                    this.txtObs.setText("El paciente no tiene dosis aplicadas");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún paciente con esa cédula...", "PACIENTE NO ENCONTRADO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPacienteActionPerformed
        String cedula = this.txtCedPaciente.getText();
        String nombre = this.txtNomPaciente.getText();
        String telefono = this.txtTelPaciente.getText();
        String direccion = this.txtDirPaciente.getText();
        String edad = this.txtEdadPaciente.getText();
        String observacion = this.txtObs.getText();

        if (cedula.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || direccion.isEmpty() || edad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Para modificar la información no pueden haber campos vacíos...", "FALTA INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Paciente pac = new Paciente(cedula, nombre, telefono, direccion, Integer.parseInt(edad));
            boolean modificar = this.inicio.getControlador().modificarPaciente(pac);
            if (modificar) {
                this.borrarCampos();
                JOptionPane.showMessageDialog(this, "Se ha modificado la información del paciente exitosamente", "PACIENTE MODIFICADO", JOptionPane.PLAIN_MESSAGE, this.icono_exito);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo modificar la información del paciente...", "PACIENTE NO MODIFICADO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnModificarPacienteActionPerformed

    private void btnBuscarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVacunaActionPerformed
        String cedula = this.txtCedVacuna.getText();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la cédula para buscar al paciente...", "FALTA INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Paciente pac = this.inicio.getControlador().buscarPaciente(cedula);
            if (pac != null) {
                ArrayList<Paciente_vacuna> pv = this.inicio.getControlador().buscarPacienteVacuna(cedula);
                if(pv.size() > 0){
                    String cad = "El paciente "+this.inicio.getControlador().buscarPaciente(pv.get(0).getPaciente()).getNombre()+"\ntiene puestas las siguientes dosis:";
                    for (int i = 0; i < pv.size(); i++) {
                        cad += "\n\nVacuna= " + this.inicio.getControlador().buscarVacunaID(pv.get(i).getVacuna()).getNombre() + 
                                "\nPuesta por= " + this.inicio.getControlador().buscarEnfermero(pv.get(i).getEnfermero()).getNombre()+ 
                                "\nFecha= " + pv.get(i).getFecha();
                        this.txtObsVacuna.setText(cad);
                    }
                }else{
                     this.txtObs.setText("El paciente no tiene dosis aplicadas");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún paciente con esa cédula...", "PACIENTE NO ENCONTRADO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarVacunaActionPerformed

    private void cmbVacunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVacunaItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            String vacuna = this.cmbVacuna.getSelectedItem().toString();
            if(vacuna.equalsIgnoreCase("Seleccionar...")){
                this.lblDosisVacuna.setText("Cantidad de vacunas en inventario");
            }else{
                ArrayList<Vacuna> listado = this.inicio.getControlador().listarVacunas();
                for(int i=0; i<listado.size(); i++){
                    if(listado.get(i).getNombre().equalsIgnoreCase(vacuna)){
                        this.lblDosisVacuna.setText("Quedan "+listado.get(i).getCantidad()+" de dosis de "+vacuna);
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbVacunaItemStateChanged

    private void btnRegistroVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVacunaActionPerformed
        String cedula = this.txtCedVacuna.getText();
        String vacuna = this.cmbVacuna.getSelectedItem().toString();
        Date date = new Date();
        String fecha = date.getDate()+"/"+(date.getMonth()+1)+"/"+(date.getYear()+1900)+" - "+date.getHours()+":"+date.getMinutes();
        
        if (cedula.isEmpty() || vacuna.equalsIgnoreCase("Seleccionar...")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la cédula del paciente y seleccionar la vacuna a aplicar...", "FALTA INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Vacuna vac = this.inicio.getControlador().buscarVacuna(vacuna);
            Paciente_vacuna pav = new Paciente_vacuna(cedula, ""+vac.getId(), this.lblEnf.getText(), fecha);
            if(vac.getCantidad()>0){
                boolean registrar = this.inicio.getControlador().registrarVacunaPuesta(pav);
                if(registrar){
                    this.borrarCampos();
                    JOptionPane.showMessageDialog(this, "Se ha registrado exitosamente", "REGISTRADO", JOptionPane.PLAIN_MESSAGE, this.icono_exito);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar...", "NO REGISTRADO", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo vacunar porque no hay dosis disponibles de la vacuna seleccionada...", "NO HAY DOSIS DE LA VACUNA SELECCIONADA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistroVacunaActionPerformed

    private void borrarCampos() {
        this.txtCedPaciente.setText("");
        this.txtNomPaciente.setText("");
        this.txtTelPaciente.setText("");
        this.txtDirPaciente.setText("");
        this.txtEdadPaciente.setText("");
        this.txtObs.setText("");
        this.txtCedVacuna.setText("");
        this.txtObsVacuna.setText("");
        this.cmbVacuna.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnBuscarVacuna;
    private javax.swing.JButton btnCerrarAdmin;
    private javax.swing.JButton btnModificarPaciente;
    private javax.swing.JButton btnRegistroPaciente;
    private javax.swing.JButton btnRegistroVacuna;
    private javax.swing.JComboBox<String> cmbVacuna;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDosisVacuna;
    private javax.swing.JLabel lblEnf;
    private javax.swing.JTextField txtCedPaciente;
    private javax.swing.JTextField txtCedVacuna;
    private javax.swing.JTextField txtDirPaciente;
    private javax.swing.JTextField txtEdadPaciente;
    private javax.swing.JTextField txtNomPaciente;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextArea txtObsVacuna;
    private javax.swing.JTextField txtTelPaciente;
    // End of variables declaration//GEN-END:variables
}
